# Generated by Django 4.1.1 on 2022-09-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LunaDeMiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Salones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon', models.CharField(max_length=40)),
                ('ciudad', models.CharField(max_length=40)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vestidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=40)),
                ('modista', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
